import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Bot } from "lucide-react";

const sofiaPro = localFont({
  src: [
    {
      path: "./fonts/SofiaProRegular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/SofiaProMedium.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/SofiaProBold.otf",
      weight: "700",
      style: "normal",
    },
  ],
});
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "RSUD Dr.Soettomo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sofiaPro.className}>
        <header className="z-50">
          <Navbar />
        </header>
        <div className=" bg-clr-300 w-14 h-14 flex items-center justify-center p-3 mb-5 mr-5 rounded-full right-0 bottom-0 fixed">
          <Bot />
        </div>
        {children}
      </body>
    </html>
  );
}
